name: YuGiOh Tokens Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: latest
          delete_release: true
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Generate checksums
        run: |
          sha256sum token.json > token.json.sha256

      - name: Create/Update release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: YuGiOh Tokens Data
          files: |
            ./token.json
            ./*.sha256
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
